version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: always
