apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: notes-app
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000