apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: notes-app
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend-deployment
        image: mahbeer/notes_app-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
